name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev libldns-dev cython3 git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install --user --upgrade setuptools
        pip install --upgrade cython==0.29.36
        pip install buildozer

    - name: Force Fix Buildozer Spec for API 33
      run: |
        if [ -f buildozer.spec ]; then
          sed -i 's/android.api =.*/android.api = 33/g' buildozer.spec
          sed -i 's/#android.api =.*/android.api = 33/g' buildozer.spec
          sed -i 's/android.minapi =.*/android.minapi = 21/g' buildozer.spec
          sed -i 's/#android.minapi =.*/android.minapi = 21/g' buildozer.spec
        fi

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
