name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev libldns-dev cython3
        pip install --upgrade pip
        pip install buildozer

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk
